{
 "title": "Go Away",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Safety",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "is_safe{}", "legendFormat": "{{ app }}" }
   ]
  },
  { "title": "Current Safety Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Living Room Window",
   "type": "gauge",
   "description": "Is Living Room Currently\n Safe",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livingroom_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Bed Room Window",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bedroom_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Garden",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "garden_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Active Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_active_devices", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Number of Burglaries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_of_total_burglaries", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Number of Actual Breaks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_of_breaks", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Living Room Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livingroom_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Bedroom Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bedroom_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Garden Lights",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "garden_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Defective Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_defective_devices", "legendFormat": "{{ app }}" }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Burglaries History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "is_safe", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Garden History",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "garden_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Living Room History",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "livingroom_break", "legendFormat": "{{ app }}" }
   ]
  },
  {
   "title": "Bedroom History",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "bedroom_break", "legendFormat": "{{ app }}" }
   ]
  }
 ]
}